/**
 * Generate test tickets for a specific user's organization.
 * Run: npx tsx prisma/generate-tickets.ts
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const TARGET_ORG_ID = 'cmly1ewdz00000inov9yvpck9'  // sf11346@gmail.com's org "Stellar"
const TARGET_USER_ID = 'c9bccbf7-b106-48ac-b83b-81e183675aad' // Maria Garcia

const ticketsData = [
  {
    subject: 'URGENT: Payment gateway returning errors',
    body: 'Since this morning, all credit card payments are failing with error code PG-5021. We have over 200 orders stuck and customers are leaving. This needs immediate attention. Our revenue is dropping by the minute.',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'URGENT',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.92,
    category: 'technical',
    language: 'en',
    summary: 'Payment gateway failures causing order blocks. ~200 stuck orders. Revenue impact.',
    customerName: 'Alex Richardson',
    customerEmail: 'alex@shopmax.com',
  },
  {
    subject: 'Can\'t access admin dashboard after password reset',
    body: 'I reset my password yesterday and now I can\'t log into the admin dashboard. It keeps saying "Invalid credentials" even though I just changed the password. I\'ve tried clearing cookies and using incognito mode.',
    channel: 'WEB',
    status: 'OPEN',
    priority: 'HIGH',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.68,
    category: 'technical',
    language: 'en',
    summary: 'Login issues after password reset. Tried cache clearing and incognito without success.',
    customerName: 'Jennifer Wu',
    customerEmail: 'jennifer@brandtech.io',
  },
  {
    subject: 'Love the new reporting feature!',
    body: 'Just wanted to say the new custom reporting feature you launched last week is amazing! We\'ve been asking for this for months and it exceeds our expectations. The drag-and-drop builder is intuitive and our marketing team is already creating weekly reports.',
    channel: 'WEB',
    status: 'RESOLVED',
    priority: 'LOW',
    sentiment: 'POSITIVE',
    sentimentScore: 0.95,
    category: 'feedback',
    language: 'en',
    summary: 'Customer very happy with new custom reporting feature. Positive feedback.',
    customerName: 'Mark Thompson',
    customerEmail: 'mark@digitalwave.co',
    assignedToId: TARGET_USER_ID,
    resolvedAt: new Date(Date.now() - 3600000),
  },
  {
    subject: 'Need bulk import for 5000 contacts',
    body: 'We\'re migrating from HubSpot and need to import about 5,000 contacts with custom fields. The current CSV import seems limited to 500 records. Is there a way to do a bulk import? We need this done by end of week.',
    channel: 'EMAIL',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    sentiment: 'NEUTRAL',
    sentimentScore: 0.50,
    category: 'onboarding',
    language: 'en',
    summary: 'Migrating from HubSpot, needs bulk import for 5K contacts. CSV limit blocking progress.',
    customerName: 'Sophie Martinez',
    customerEmail: 'sophie@growthlab.com',
    assignedToId: TARGET_USER_ID,
  },
  {
    subject: 'Consulta sobre integración con Zapier',
    body: 'Hola, estamos interesados en integrar su plataforma con Zapier para automatizar nuestros flujos de trabajo. ¿Tienen documentación sobre las acciones y triggers disponibles? También nos gustaría saber si hay algún coste adicional por la integración.',
    channel: 'WHATSAPP',
    status: 'OPEN',
    priority: 'MEDIUM',
    sentiment: 'POSITIVE',
    sentimentScore: 0.72,
    category: 'sales',
    language: 'es',
    summary: 'Inquiry about Zapier integration. Wants documentation and pricing for integration features.',
    customerName: 'Carlos Ruiz',
    customerEmail: 'carlos@agenciadigital.es',
  },
  {
    subject: 'SSL certificate error on custom domain',
    body: 'We set up our custom domain last week but users are getting SSL warnings. Chrome shows "NET::ERR_CERT_DATE_INVALID". This is killing our credibility and conversion rate. We need this fixed ASAP.',
    channel: 'SLACK',
    status: 'OPEN',
    priority: 'URGENT',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.85,
    category: 'technical',
    language: 'en',
    summary: 'SSL certificate error on custom domain. Affecting credibility and conversions.',
    customerName: 'Rachel Green',
    customerEmail: 'rachel@luxuryhomes.com',
  },
  {
    subject: 'Invoice too high this month - possible error?',
    body: 'Our monthly invoice jumped from $299 to $847 this month. We haven\'t changed our plan or added any new features. Could you break down what caused this increase? Seems like there might be an error on extra API calls that we didn\'t make.',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'HIGH',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.70,
    category: 'billing',
    language: 'en',
    summary: 'Invoice increased from $299 to $847 unexpectedly. Customer suspects billing error on API call charges.',
    customerName: 'Daniel Park',
    customerEmail: 'daniel@fintechsolve.com',
  },
  {
    subject: 'Feature request: Whatsapp Business API integration',
    body: 'We\'d love to see native WhatsApp Business API integration. Currently we\'re using a third-party connector and it\'s unreliable. Having it built-in would be a game changer for our customer support flow. Our team handles about 500 WhatsApp messages daily.',
    channel: 'WEB',
    status: 'OPEN',
    priority: 'LOW',
    sentiment: 'POSITIVE',
    sentimentScore: 0.78,
    category: 'feedback',
    language: 'en',
    summary: 'Feature request for native WhatsApp Business API. Customer processes 500 msgs/day through unreliable third-party.',
    customerName: 'Priya Sharma',
    customerEmail: 'priya@connectindia.in',
  },
  {
    subject: 'Our team needs training on the new analytics module',
    body: 'Hi, we recently upgraded to Pro and our team of 12 is struggling with the advanced analytics module. Could we schedule a group training session? Preferably next Tuesday or Wednesday afternoon. We\'re in EST timezone.',
    channel: 'EMAIL',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    sentiment: 'NEUTRAL',
    sentimentScore: 0.55,
    category: 'onboarding',
    language: 'en',
    summary: 'Team of 12 needs training on analytics module after Pro upgrade. Wants session next Tue/Wed.',
    customerName: 'Lisa Chen',
    customerEmail: 'lisa@mediagroup.com',
    assignedToId: TARGET_USER_ID,
  },
  {
    subject: 'Terrible experience with support chat',
    body: 'I waited 45 minutes in your support chat only to be told my issue needs to be escalated. Then I was disconnected. This is the third time this month. Your chat support is absolutely useless. I\'m seriously considering switching to a competitor.',
    channel: 'WEB',
    status: 'OPEN',
    priority: 'HIGH',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.93,
    category: 'complaint',
    language: 'en',
    summary: 'Very frustrated with chat support. 45min wait, disconnected, third time this month. Churn risk.',
    customerName: 'Mike Davis',
    customerEmail: 'mike@ecomstore.com',
  },
  {
    subject: 'Automation workflow stopped working',
    body: 'Our automated email sequence that sends onboarding emails to new users stopped firing yesterday. We\'ve verified the trigger conditions and they look correct. About 150 new users haven\'t received their welcome emails.',
    channel: 'SLACK',
    status: 'OPEN',
    priority: 'HIGH',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.65,
    category: 'technical',
    language: 'en',
    summary: 'Email automation workflow broken since yesterday. 150 users missing welcome emails.',
    customerName: 'James Mitchell',
    customerEmail: 'james@saasify.co',
  },
  {
    subject: 'Requesting API rate limit increase',
    body: 'We\'re hitting the API rate limit (1000 req/min) during our peak traffic hours (2-6 PM EST). Our application serves about 50K active users and we need at least 5000 req/min. Is this possible on our current Pro plan?',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'MEDIUM',
    sentiment: 'NEUTRAL',
    sentimentScore: 0.48,
    category: 'technical',
    language: 'en',
    summary: 'API rate limit insufficient for 50K users. Needs 5x increase from 1000 to 5000 req/min.',
    customerName: 'Tom Baker',
    customerEmail: 'tom@dataflow.io',
  },
  {
    subject: 'Démonstration pour notre équipe de direction',
    body: 'Bonjour, nous sommes une agence de 200 personnes et nous envisageons d\'adopter votre plateforme. Pourriez-vous organiser une démonstration pour notre comité de direction la semaine prochaine? Nous sommes particulièrement intéressés par les fonctionnalités d\'IA et d\'automatisation.',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'HIGH',
    sentiment: 'POSITIVE',
    sentimentScore: 0.82,
    category: 'sales',
    language: 'fr',
    summary: '200-person agency interested in platform. Wants executive demo, focused on AI and automation. High-value prospect.',
    customerName: 'Marie Laurent',
    customerEmail: 'marie@agencenouvelle.fr',
  },
  {
    subject: 'Data export not including all custom fields',
    body: 'When I export our customer data to CSV, the custom fields "Source Channel" and "Lead Score" are missing from the export. These are critical for our reporting. This used to work fine last month. Is there a bug?',
    channel: 'WEB',
    status: 'OPEN',
    priority: 'MEDIUM',
    sentiment: 'NEUTRAL',
    sentimentScore: 0.52,
    category: 'technical',
    language: 'en',
    summary: 'CSV export missing custom fields that previously worked. Regression bug suspected.',
    customerName: 'Amy Rodriguez',
    customerEmail: 'amy@analyticsco.com',
  },
  {
    subject: 'Renewal discount request - loyal customer',
    body: 'We\'ve been customers for 3 years now on the Enterprise plan. Our contract is up for renewal next month and we were hoping to discuss a loyalty discount. We\'ve referred 4 other companies to you. Would appreciate a call to discuss options.',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'MEDIUM',
    sentiment: 'POSITIVE',
    sentimentScore: 0.75,
    category: 'sales',
    language: 'en',
    summary: '3-year Enterprise customer requesting renewal discount. Has referred 4 companies. Retention priority.',
    customerName: 'Chris Anderson',
    customerEmail: 'chris@enterprise-solutions.com',
  },
  {
    subject: 'Mobile app crashes on iOS 18',
    body: 'Since updating to iOS 18, the mobile app crashes immediately on launch. I\'ve tried reinstalling and restarting my phone. This affects at least 5 people in our team. We rely on the mobile app for field work.',
    channel: 'WHATSAPP',
    status: 'OPEN',
    priority: 'HIGH',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.72,
    category: 'technical',
    language: 'en',
    summary: 'iOS 18 crash-on-launch bug. Affects multiple team members. Used for field work.',
    customerName: 'Eva Collins',
    customerEmail: 'eva@fieldteam.co',
  },
  {
    subject: 'Excellent onboarding experience!',
    body: 'I just wanted to send a quick note to say how impressed we are with the onboarding process. Your team member Sarah was incredibly helpful and patient. She went above and beyond to help us migrate our data. We\'re already seeing productivity improvements!',
    channel: 'WEB',
    status: 'CLOSED',
    priority: 'LOW',
    sentiment: 'POSITIVE',
    sentimentScore: 0.97,
    category: 'feedback',
    language: 'en',
    summary: 'Extremely positive feedback about onboarding, specifically praising team member Sarah. Productivity gains.',
    customerName: 'Kevin Zhang',
    customerEmail: 'kevin@startupflow.com',
    assignedToId: TARGET_USER_ID,
    resolvedAt: new Date(Date.now() - 172800000),
  },
  {
    subject: 'Webhook deliveries failing silently',
    body: 'We set up webhooks to notify our system of new events but about 30% of them aren\'t being delivered. No errors in your dashboard, no retry attempts visible. We only discovered this by comparing logs on our end. This is causing data sync issues.',
    channel: 'SLACK',
    status: 'OPEN',
    priority: 'HIGH',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.67,
    category: 'technical',
    language: 'en',
    summary: 'Silent webhook delivery failures (~30%). No error logging or retries. Data sync impact.',
    customerName: 'Nathan Cole',
    customerEmail: 'nathan@devhub.io',
  },
  {
    subject: 'Presupuesto para campaña de Black Friday',
    body: 'Necesitamos preparar nuestra infraestructura para Black Friday. El año pasado tuvimos 10x más tráfico y la plataforma se cayó. Queremos evitar eso. ¿Pueden darnos un presupuesto para escalar temporalmente nuestros recursos durante noviembre?',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'MEDIUM',
    sentiment: 'NEUTRAL',
    sentimentScore: 0.55,
    category: 'sales',
    language: 'es',
    summary: 'Black Friday scaling request. Previous year had 10x traffic spike and outage. Needs temporary scaling quote.',
    customerName: 'Lucia Fernandez',
    customerEmail: 'lucia@tiendaonline.es',
  },
  {
    subject: 'GDPR compliance - data deletion request',
    body: 'Under GDPR Article 17, we need to confirm that all data for the following customer accounts has been permanently deleted: accounts #4521, #4522, #4523. Please provide written confirmation within 30 days as required by regulation.',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'HIGH',
    sentiment: 'NEUTRAL',
    sentimentScore: 0.45,
    category: 'compliance',
    language: 'en',
    summary: 'GDPR Article 17 data deletion request for 3 accounts. Written confirmation required within 30 days.',
    customerName: 'Emma Wagner',
    customerEmail: 'emma@legalcorp.de',
  },
  {
    subject: 'Two-factor authentication not sending SMS',
    body: 'I\'ve been trying to log in for the past hour but the 2FA SMS code never arrives. I\'ve checked my phone number is correct. Other SMS from other services work fine. This is blocking me from accessing critical data for a client meeting in 2 hours.',
    channel: 'WHATSAPP',
    status: 'OPEN',
    priority: 'URGENT',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.80,
    category: 'technical',
    language: 'en',
    summary: '2FA SMS not delivering. User locked out with client meeting in 2 hours. Time-critical.',
    customerName: 'Ryan Mitchell',
    customerEmail: 'ryan@consultpro.com',
  },
  {
    subject: 'Custom dashboard widgets loading slowly',
    body: 'Our custom dashboard with 8 widgets takes about 45 seconds to fully load. It was instant last month. Each widget seems to load sequentially rather than in parallel. Performance has degraded significantly and it\'s affecting our daily standup meetings.',
    channel: 'WEB',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    sentiment: 'NEGATIVE',
    sentimentScore: 0.60,
    category: 'technical',
    language: 'en',
    summary: 'Dashboard loading 45s (was instant). Sequential widget loading regression. Affects daily standups.',
    customerName: 'Olivia Peters',
    customerEmail: 'olivia@speedytech.com',
    assignedToId: TARGET_USER_ID,
  },
  {
    subject: 'Want to add 50 new team seats',
    body: 'Great news - we\'re expanding our usage! We need to add 50 additional team seats to our Enterprise plan. Can you help with bulk seat pricing? Also, can these be added mid-billing cycle or do we need to wait for renewal?',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'MEDIUM',
    sentiment: 'POSITIVE',
    sentimentScore: 0.88,
    category: 'sales',
    language: 'en',
    summary: 'Enterprise expansion - 50 new seats. Asking about bulk pricing and mid-cycle addition. Upsell opportunity.',
    customerName: 'Sarah O\'Brien',
    customerEmail: 'sarah@bigcorp.com',
  },
  {
    subject: 'Report: Phishing email impersonating your company',
    body: 'We received an email that looks like it\'s from your company asking us to "verify our account" by clicking a suspicious link. The sender domain is support@y0ur-company.com (with a zero). Wanted to alert you in case other customers are being targeted.',
    channel: 'EMAIL',
    status: 'OPEN',
    priority: 'URGENT',
    sentiment: 'NEUTRAL',
    sentimentScore: 0.50,
    category: 'security',
    language: 'en',
    summary: 'Customer reporting phishing attempt impersonating company. Suspicious domain with zero in name.',
    customerName: 'Greg Morrison',
    customerEmail: 'greg@securecorp.com',
  },
  {
    subject: 'Sugerencia: mejorar el editor de emails',
    body: 'El editor de emails es funcional pero le falta un modo de vista previa para móvil. Muchos de nuestros clientes abren los emails en el teléfono y no podemos verificar cómo se ve antes de enviar. Sería genial poder hacer preview responsivo.',
    channel: 'WEB',
    status: 'OPEN',
    priority: 'LOW',
    sentiment: 'POSITIVE',
    sentimentScore: 0.70,
    category: 'feedback',
    language: 'es',
    summary: 'Feature request: mobile preview mode for email editor. Many clients open on mobile.',
    customerName: 'Pablo Navarro',
    customerEmail: 'pablo@creativostudio.mx',
  },
]

async function main() {
  console.log('🎫 Generating test tickets for org:', TARGET_ORG_ID)
  console.log()

  // Stagger createdAt times so they appear spread over the last 7 days
  const now = Date.now()

  for (let i = 0; i < ticketsData.length; i++) {
    const td = ticketsData[i] as any
    // Spread tickets over last 7 days
    const ageMs = Math.floor((i / ticketsData.length) * 7 * 24 * 60 * 60 * 1000)
    const createdAt = new Date(now - ageMs)

    const ticket = await prisma.ticket.create({
      data: {
        subject: td.subject,
        body: td.body,
        channel: td.channel,
        status: td.status,
        priority: td.priority,
        sentiment: td.sentiment,
        sentimentScore: td.sentimentScore,
        category: td.category,
        language: td.language,
        summary: td.summary,
        customerName: td.customerName,
        customerEmail: td.customerEmail,
        assignedToId: td.assignedToId ?? null,
        resolvedAt: td.resolvedAt ?? null,
        orgId: TARGET_ORG_ID,
        createdAt,
      },
    })

    // Customer initial message
    await prisma.ticketMessage.create({
      data: {
        ticketId: ticket.id,
        body: td.body,
        senderType: 'CUSTOMER',
        senderName: td.customerName,
        createdAt,
      },
    })

    // AI suggestion for open/in-progress
    if (td.status === 'OPEN' || td.status === 'IN_PROGRESS') {
      await prisma.aiSuggestion.create({
        data: {
          ticketId: ticket.id,
          suggestedReply: generateReply(td.category, td.sentiment),
          confidence: Math.random() * 0.3 + 0.65,
          accepted: null,
          createdAt: new Date(createdAt.getTime() + 30000),
        },
      })
    }

    const icon = td.sentiment === 'POSITIVE' ? '😊' : td.sentiment === 'NEGATIVE' ? '😠' : '😐'
    console.log(`  ${icon} [${td.priority.padEnd(6)}] ${td.subject.substring(0, 55)}...`)
  }

  console.log()
  console.log(`✅ Created ${ticketsData.length} test tickets!`)
  console.log(`   Org: ${TARGET_ORG_ID}`)
}

function generateReply(category: string, sentiment: string): string {
  const replies: Record<string, string> = {
    technical: 'Thank you for reporting this issue. I\'ve escalated it to our technical team for immediate investigation. We\'ll provide an update within the next 30 minutes.',
    billing: 'Thank you for bringing this billing concern to our attention. I\'ve flagged your account for review. You can expect a detailed response within 24 hours.',
    sales: 'Thank you for your interest! I\'d be happy to walk you through our options. Let me prepare a personalized proposal for your team.',
    feedback: 'Thank you so much for your kind words! Your feedback means a lot to our team and motivates us to keep improving.',
    complaint: 'I sincerely apologize for the frustration you\'ve experienced. This is not the level of service we strive for. I\'m personally escalating your case.',
    cancellation: 'I\'m sorry to hear you\'re considering leaving. Before processing, I\'d love to understand what hasn\'t met your needs.',
    onboarding: 'Welcome aboard! I\'ll send you our step-by-step guide and schedule a quick walkthrough session.',
    compliance: 'Thank you for your compliance request. I\'ve escalated this to our Data Protection Officer for immediate processing.',
    security: 'Thank you for alerting us to this security concern. Our security team has been notified and is investigating immediately.',
    general: 'Thank you for reaching out. I\'ve reviewed your message and will get back to you with a detailed response shortly.',
  }
  const prefix = sentiment === 'NEGATIVE' ? 'I understand your frustration. ' : ''
  return prefix + (replies[category] || replies.general)
}

main()
  .catch((e) => { console.error('❌ Failed:', e); process.exit(1) })
  .finally(() => prisma.$disconnect())
